# Generated by Django 3.0.7 on 2020-08-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20200728_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
